#!/bin/bash 

function result_check {
    if [ "$?" != "0" ]; then
        exit;
    fi
}

red=`tput setaf 1`
green=`tput setaf 2`
reset=`tput sgr0`

print_line() {
    echo ""
}

print_green() {
    print_line
    echo "${green}-> $1 ${reset}"
}

print_red() {
    print_line
    echo "${red}-> $1 ${reset}"
}

function valid_ip()
{
    local  ip=$1
    local  stat=1

    if [[ $ip =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
        OIFS=$IFS
        IFS='.'
        ip=($ip)
        IFS=$OIFS
        [[ ${ip[0]} -le 255 && ${ip[1]} -le 255 \
            && ${ip[2]} -le 255 && ${ip[3]} -le 255 ]]
        stat=$?
    fi
    return $stat
}

if ! valid_ip $1  
then
	print_red "!!!ip addr is invalid"
	exit -1; 
fi

project_dir=$(dirname $(dirname $(realpath $0)))

hicarsdk_dir="${project_dir}/3rd/hicar_sdk"

print_green "hicarsdk dir : ${hicarsdk_dir}"
if [ ! -d "${hicarsdk_dir}" ]; then
    print_red "!!!hicarsdk dir is empty"
    exit -1;
fi

print_green "upload hicarsdk"
scp ${hicarsdk_dir}/lib/* root@$1:/usr/lib && ssh root@$1 "sync; sync; sync"
