/*
 * Generated by gdbus-codegen 2.40.2. DO NOT EDIT.
 *
 * The license of this code is the same as for the source it was derived from.
 */

#ifndef __HSAEBLE_H__
#define __HSAEBLE_H__

#include <gio/gio.h>

G_BEGIN_DECLS


/* ------------------------------------------------------------------------ */
/* Declarations for com.hsaeyz.bluetooth.hsaeble */

#define TYPE_HSAEBLE (hsaeble_get_type ())
#define HSAEBLE(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_HSAEBLE, Hsaeble))
#define IS_HSAEBLE(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_HSAEBLE))
#define HSAEBLE_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), TYPE_HSAEBLE, HsaebleIface))

struct _Hsaeble;
typedef struct _Hsaeble Hsaeble;
typedef struct _HsaebleIface HsaebleIface;

struct _HsaebleIface
{
  GTypeInterface parent_iface;


  gboolean (*handle_start_ble_advertise) (
    Hsaeble *object,
    GDBusMethodInvocation *invocation,
    GVariant *arg_data,
    gint arg_datalen);

  gboolean (*handle_stop_ble_advertise) (
    Hsaeble *object,
    GDBusMethodInvocation *invocation);

  gboolean  (*get_ibroadcast) (Hsaeble *object);

};

GType hsaeble_get_type (void) G_GNUC_CONST;

GDBusInterfaceInfo *hsaeble_interface_info (void);
guint hsaeble_override_properties (GObjectClass *klass, guint property_id_begin);


/* D-Bus method call completion functions: */
void hsaeble_complete_start_ble_advertise (
    Hsaeble *object,
    GDBusMethodInvocation *invocation);

void hsaeble_complete_stop_ble_advertise (
    Hsaeble *object,
    GDBusMethodInvocation *invocation);



/* D-Bus method calls: */
void hsaeble_call_start_ble_advertise (
    Hsaeble *proxy,
    GVariant *arg_data,
    gint arg_datalen,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean hsaeble_call_start_ble_advertise_finish (
    Hsaeble *proxy,
    GAsyncResult *res,
    GError **error);

gboolean hsaeble_call_start_ble_advertise_sync (
    Hsaeble *proxy,
    GVariant *arg_data,
    gint arg_datalen,
    GCancellable *cancellable,
    GError **error);

void hsaeble_call_stop_ble_advertise (
    Hsaeble *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean hsaeble_call_stop_ble_advertise_finish (
    Hsaeble *proxy,
    GAsyncResult *res,
    GError **error);

gboolean hsaeble_call_stop_ble_advertise_sync (
    Hsaeble *proxy,
    GCancellable *cancellable,
    GError **error);



/* D-Bus property accessors: */
gboolean hsaeble_get_ibroadcast (Hsaeble *object);
void hsaeble_set_ibroadcast (Hsaeble *object, gboolean value);


/* ---- */

#define TYPE_HSAEBLE_PROXY (hsaeble_proxy_get_type ())
#define HSAEBLE_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_HSAEBLE_PROXY, HsaebleProxy))
#define HSAEBLE_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), TYPE_HSAEBLE_PROXY, HsaebleProxyClass))
#define HSAEBLE_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TYPE_HSAEBLE_PROXY, HsaebleProxyClass))
#define IS_HSAEBLE_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_HSAEBLE_PROXY))
#define IS_HSAEBLE_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), TYPE_HSAEBLE_PROXY))

typedef struct _HsaebleProxy HsaebleProxy;
typedef struct _HsaebleProxyClass HsaebleProxyClass;
typedef struct _HsaebleProxyPrivate HsaebleProxyPrivate;

struct _HsaebleProxy
{
  /*< private >*/
  GDBusProxy parent_instance;
  HsaebleProxyPrivate *priv;
};

struct _HsaebleProxyClass
{
  GDBusProxyClass parent_class;
};

GType hsaeble_proxy_get_type (void) G_GNUC_CONST;

void hsaeble_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
Hsaeble *hsaeble_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error);
Hsaeble *hsaeble_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);

void hsaeble_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
Hsaeble *hsaeble_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
Hsaeble *hsaeble_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);


/* ---- */

#define TYPE_HSAEBLE_SKELETON (hsaeble_skeleton_get_type ())
#define HSAEBLE_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_HSAEBLE_SKELETON, HsaebleSkeleton))
#define HSAEBLE_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), TYPE_HSAEBLE_SKELETON, HsaebleSkeletonClass))
#define HSAEBLE_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TYPE_HSAEBLE_SKELETON, HsaebleSkeletonClass))
#define IS_HSAEBLE_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_HSAEBLE_SKELETON))
#define IS_HSAEBLE_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), TYPE_HSAEBLE_SKELETON))

typedef struct _HsaebleSkeleton HsaebleSkeleton;
typedef struct _HsaebleSkeletonClass HsaebleSkeletonClass;
typedef struct _HsaebleSkeletonPrivate HsaebleSkeletonPrivate;

struct _HsaebleSkeleton
{
  /*< private >*/
  GDBusInterfaceSkeleton parent_instance;
  HsaebleSkeletonPrivate *priv;
};

struct _HsaebleSkeletonClass
{
  GDBusInterfaceSkeletonClass parent_class;
};

GType hsaeble_skeleton_get_type (void) G_GNUC_CONST;

Hsaeble *hsaeble_skeleton_new (void);


G_END_DECLS

#endif /* __HSAEBLE_H__ */
